config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :email_addresses, :except => [:index, :show]

  resources :phone_numbers, :except => [:index, :show]

  resources :people

end

app/models/company.rb
class Company < ActiveRecord::Base
  include Contact
  validates :name, presence: true

  def to_s
    "#{name}"
  end
end

app/models/contact.rb
module Contact
  extend ActiveSupport::Concern

  included do
    has_many :phone_numbers, as: :contact
    has_many :email_addresses, as: :contact
  end

  module ClassMethods
  end

end

app/models/email_address.rb
class EmailAddress < ActiveRecord::Base
  validates :email, :contact_id, presence: true
  belongs_to :contact, polymorphic: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  include Contact
  validates :first_name, :last_name, presence: true

  def to_s
    "#{last_name}, #{first_name}"
  end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  validates :number, :contact_id, presence: true
  belongs_to :contact, polymorphic: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def find_resource
    class_name = params[:controller].singularize
    klass      = class_name.camelize.constantize
    self.instance_variable_set "@" + class_name, klass.find(params[:id])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_resource, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/email_addresses_controller.rb
class EmailAddressesController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  def new
    @email_address = EmailAddress.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  def edit
  end

  def create
    @email_address = EmailAddress.new(email_address_params)

    respond_to do |format|
      if @email_address.save
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully created.' }
        format.json { render :show, status: :created, location: @email_address }
      else
        format.html { render :new }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @email_address.update(email_address_params)
        format.html { redirect_to @email_address.contact, notice: 'Email address was successfully updated.' }
        format.json { render :show, status: :ok, location: @email_address }
      else
        format.html { render :edit }
        format.json { render json: @email_address.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @email_address.destroy
    respond_to do |format|
      format.html { redirect_to @email_address.contact, notice: 'Email address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def email_address_params
      params.require(:email_address).permit(:email, :contact_id, :contact_type)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :find_resource, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.all
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def person_params
      params.require(:person).permit(:first_name, :last_name, :contact_type)
    end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :find_resource, only: [:edit, :update, :destroy]

  def new
    @phone_number = PhoneNumber.new(contact_id: params[:contact_id], contact_type: params[:contact_type])
  end

  def edit
  end

  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to @phone_number.contact, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def phone_number_params
      params.require(:phone_number).permit(:number, :contact_id, :contact_type)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/email_addresses_helper.rb
module EmailAddressesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>@company.name</h1>

<%= render 'form' %>

<ul class="actions">
  <li><%= link_to 'Show', @company %></li>
  <li><%= link_to 'Back', companies_path %></li>
</ul>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td>
          <ul class="actions">
            <li><%= link_to 'Show', company %></li>
            <li><%= link_to 'Edit', edit_company_path(company) %></li>
            <li><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, id: "new company" %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class= "company"

<p id="notice"><%= notice %></p>


<strong><%= @company.name %></strong>



<%= render 'phone_numbers/phone_numbers', :phone_numbers => @company.phone_numbers %>

<%= render 'email_addresses/email_addresses', :email_addresses => @company.email_addresses %>

<ul class="actions">
  <li><%= link_to "Add phone number", new_phone_number_path(contact_id: @company.id, contact_type: 'Company')%></li>
  <li><%= link_to "Add email address", new_email_address_path(contact_id: @company.id, contact_type: 'Company')%></li>
  <li><%= link_to 'Edit', edit_company_path(@company) %></li>
  <li><%= link_to 'Back', companies_path %></li>
</ul>
</div>

app/views/email_addresses/_email_addresses.html.erb
<p>
  <% email_addresses.each do |email| %>
    <li><%= email.email %>
        <%= link_to 'edit', edit_email_address_path(email)%>
        <%= link_to 'delete', email, method: :delete %></li>
  <% end %>
</p>

app/views/email_addresses/_form.html.erb
<%= form_for(@email_address) do |f| %>
  <% if @email_address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_address.errors.count, "error") %> prohibited this email_address from being saved:</h2>

      <ul>
      <% @email_address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <%= f.hidden_field :contact_id %>
  <%= f.hidden_field :contact_type %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_addresses/edit.html.erb
<h1>Editing email_address</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_address %> |
<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/index.html.erb
<h1>Listing email_addresses</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_addresses.each do |email_address| %>
      <tr>
        <td><%= email_address.email %></td>
        <td><%= email_address.contact_id %></td>
        <td><%= link_to 'Show', email_address %></td>
        <td><%= link_to 'Edit', edit_email_address_path(email_address) %></td>
        <td><%= link_to 'Destroy', email_address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Email address', new_email_address_path %>

app/views/email_addresses/new.html.erb
<h1>New email address for <%= @email_address.contact %></h1>

<%= render 'form' %>

<%= link_to 'Back', email_addresses_path %>

app/views/email_addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @email_address.email %>
</p>

<p>
  <strong>Person:</strong>
  <%= @email_address.contact_id %>
</p>

<%= link_to 'Edit', edit_email_address_path(@email_address) %> |
<%= link_to 'Back', email_addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1><%= @person.first_name %> <%= @person.last_name %></h1>

<%= render 'form' %>

<ul class="actions">
  <li><%= link_to 'Show', @person %></li> |
  <li><%= link_to 'Back', people_path %></li>
</ul>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name%> <%= person.last_name %></td>
        <td>
          <ul class ="actions">
            <li><%= link_to 'Show', person %></li>
            <li><%= link_to 'Edit', edit_person_path(person) %></li>
            <li><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="new_person"><%= link_to 'New Person', new_person_path %></div>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<div class="person">
<p id="notice"><%= notice %></p>

<strong><%= @person.first_name %> <%= @person.last_name %></strong>


<%= render 'phone_numbers/phone_numbers', :phone_numbers => @person.phone_numbers %>
<%= render 'email_addresses/email_addresses', :email_addresses =>@person.email_addresses %>

<ul class="actions">
  <li><%= link_to "Add phone number", new_phone_number_path(contact_id: @person.id, contact_type: 'Person')%></li>
  <li><%= link_to "Add email address", new_email_address_path(contact_id: @person.id, contact_type: 'Person') %></li>
  <li><%= link_to 'Edit', edit_person_path(@person) %></li>
  <li><%= link_to 'Back', people_path %></li>
</ul>
</div>

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.hidden_field :contact_id %>
    <%= f.hidden_field :contact_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/_phone_numbers.html.erb
<ul>
  <% phone_numbers.each do |phone| %>
    <li><%= phone.number %>
        <%= link_to 'edit', edit_phone_number_path(phone)%>
        <%= link_to 'delete', phone, method: :delete %></li>
  <% end %>
</ul>

app/views/phone_numbers/edit.html.erb
<h1>Editing phone_number</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<h1>Listing phone_numbers</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.number %></td>
        <td><%= phone_number.contact_id %></td>
        <td><%= link_to 'Show', phone_number %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number) %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone number', new_phone_number_path %>

app/views/phone_numbers/new.html.erb
<h1>New phone_number</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @phone_number.number %>
</p>

<p>
  <strong>Person:</strong>
  <%= @phone_number.contact_id %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number) %> |
<%= link_to 'Back', phone_numbers_path %>